# Generated by Django 5.2.1 on 2025-06-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='profile_name',
            new_name='profile',
        ),
    ]
