# Generated by Django 5.2.1 on 2025-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_resume_file_resume_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resume_thumbnails/'),
        ),
    ]
