# Generated by Django 5.2.1 on 2025-06-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_resume_uploaded_at_resume_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('profile_image', models.ImageField(upload_to='hero/')),
                ('show_resume_button', models.BooleanField(default=True)),
                ('show_contact_button', models.BooleanField(default=True)),
            ],
        ),
    ]
