# Generated by Django 5.2.1 on 2025-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_sociallink_delete_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
