# Generated by Django 5.2.1 on 2025-06-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_sociallink_email_alter_sociallink_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(max_length=100),
        ),
    ]
