# Generated by Django 5.2.3 on 2025-06-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
